settings:
# Break block mode: none, first, last, all
# None - Disables plugin, first - breaks the block the piston moves, last - breaks the block being 
# pushed into an un-pushable block, all - breaks the entire stack of blocks between first and last.
  break_block_mode: 
    last

breakable_blocks:
  - 1             # Stone
  - 2             # Grass Block
  - 3             # Dirt
  - 4             # Cobblestone
  - 12            # Sand
  - 13            # Gravel
  - 17            # Wood
  - 24            # Sandstone
  - 86            # Pumpkin
  - 103           # Melon
  - 121           # End Stone