name: BlockCrusher

main: com.github.majora2007.blockcrusher.BlockCrusher
version: 1.0
commands:
    blockcrusher:
        aliases: [bc]
        usage: |
            /<command> reload
            /<command> help
    
    reload:
        description: Reloads the configuration.
        permission: blockcrusher.reload
        usage: /<command> reload
    help:
        description: Displays help.
        permission: blockcrusher.help
        usage: /<command> help
