name: BlockCrusher

main: com.github.majora2007.blockcrusher.BlockCrusher
version: 1.0
commands:
    blockcrusher:
        description: Reloads the config
        usage: /blockcrusher help
        alias: bc
    bc:
        description: Reloads the config
        usage: /bc help
