name: BlockCrusher

main: com.github.majora2007.blockcrusher.BlockCrusher
version: 1.0
commands:
    blockcrusher:
        aliases: [bc]
        usage: |
            /<command> reload
            /<command> help
